name: Deploy to staging

on:
  push:
    branches: [ main ]

jobs:
  redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ubuntu@35.154.216.90 "
            cd test_ci_cd &&
            git pull origin main &&
            corepack prepare pnpm@latest --activate &&
            pnpm install &&
            pnpm run build &&
            pm2 restart fe-sever &&
            pm2 restart http-sever &&
            pm2 restart ws-sever
          "
